const messages = {
  'zh-Hans': {
    'brand.sub': 'CONTROL PLATFORM', 'nav.capabilities': '能力', 'nav.workflow': '流程', 'nav.software': '软件体验', 'nav.markets': '行业场景', 'nav.contact': '联系团队 ↗', 'control.languageLabel': '语言',
    'hero.eyebrow': 'DALI CONTROL PLATFORM / V1.0', 'hero.title': '让每一条总线，<em>为下一场景</em>做好准备。', 'hero.description': '面向专业照明工程的控制器与上位机工作台。以国际标准为基础，把搜索、寻址、分组、场景、参数与调光收拢成一条可交付、可维护的工程路径。', 'hero.primary': '查看产品能力 ↓', 'hero.secondary': '获取合作资料 ↗', 'hero.footnote': '面向调试团队、系统集成商与照明 OEM 设计。', 'hero.visualLabel': 'LIVE WORKSPACE PREVIEW', 'hero.visualCaption': '工程首页 · 状态总览', 'common.online': '在线',
    'metric.lineLabel': 'DALI LINE', 'metric.lineSub': 'Ready to commission', 'metric.signalLabel': 'BUS SIGNAL', 'metric.signalSub': 'Stable link',
    'standards.lead': 'Designed around the standards your projects already trust.', 'proof.platforms': '覆盖平台', 'proof.platformsSub': 'Windows · macOS · iOS · Android', 'proof.workflow': '条完整工程路径', 'proof.workflowSub': '从发现到交付，减少工具切换', 'proof.scenes': '场景位', 'proof.scenesSub': '让空间逻辑可复用、可维护', 'proof.addresses': '短地址视图', 'proof.addressesSub': '以总线对象为中心组织工作',
    'capabilities.eyebrow': 'ONE SYSTEM / MANY MOMENTS', 'capabilities.title': '把工程复杂度，<br /><em>交给一套清晰的工作台。</em>', 'capabilities.intro': '从首次发现设备，到项目交付后的维护，产品能力沿着工程团队真实的工作顺序展开。每一步都有明确对象、状态和结果。',
    'capability.discovery.title': '发现与识别', 'capability.discovery.body': '快速建立控制器与 DALI Line 视图，支持全新搜索、扩展搜索和连接状态确认。', 'capability.discovery.tag': 'Commissioning start', 'capability.address.title': '地址与拓扑', 'capability.address.body': '读取、设定与重分配短地址，按地址、群组和总线对象组织现场工作。', 'capability.address.tag': 'Addressing', 'capability.scene.title': '分组与场景', 'capability.scene.body': '把空间意图沉淀为可读取、可复用的分组与场景逻辑。', 'capability.scene.tag': 'Space logic', 'capability.parameters.title': '参数与批量配置', 'capability.parameters.body': '围绕亮度、渐变、范围和设备参数，提供清晰的读取、设定和批量运维入口。', 'capability.parameters.tag': 'Fleet ready', 'capability.control.title': '实时调光与色彩', 'capability.control.body': '支持广播、组与单地址控制，覆盖开关、亮度、色温及 RGBWAF 彩色应用。', 'capability.control.tag': 'DT8 control', 'capability.lifecycle.title': '连接、升级与交付', 'capability.lifecycle.body': 'Type-C 与 LAN 接入，配合固件升级和工程快照，让项目从现场调试走向长期运维。', 'capability.lifecycle.tag': 'Lifecycle',
    'workflow.eyebrow': 'FROM FIRST SCAN TO LASTING VALUE', 'workflow.title': '一条可交付的<br /><em>工程节奏。</em>', 'workflow.intro': '把“能控制”推进到“能复制、能交付、能持续维护”。每个阶段都围绕现场团队最关心的下一步动作。', 'workflow.discover.title': 'Discover', 'workflow.discover.body': '发现控制器与总线设备', 'workflow.address.title': 'Address', 'workflow.address.body': '建立清晰的地址与拓扑', 'workflow.compose.title': 'Compose', 'workflow.compose.body': '配置分组与场景逻辑', 'workflow.tune.title': 'Tune', 'workflow.tune.body': '批量设定关键参数', 'workflow.operate.title': 'Operate', 'workflow.operate.body': '现场调光与状态确认', 'workflow.maintain.title': 'Maintain', 'workflow.maintain.body': '升级、诊断与持续交付',
    'software.eyebrow': 'SOFTWARE EXPERIENCE', 'software.title': '让现场团队，<br /><em>一眼看懂。</em>', 'software.intro': '专业能力不应被复杂界面遮蔽。工作台围绕线路、对象、状态和下一步操作组织信息，让工程团队快速判断并持续推进。', 'screen.dashboard.title': '工程总览', 'screen.dashboard.sub': '快速掌握项目状态', 'screen.dashboard.body': '设备、在线状态、故障与常用区域集中在同一视图中。', 'screen.control.title': '实时控制', 'screen.control.sub': '开关、亮度与色温', 'screen.control.body': '从广播到单地址，每一次现场操作都清晰可见。', 'screen.parameters.title': '参数配置', 'screen.parameters.sub': '批量维护与精细设置', 'screen.parameters.body': '在聚焦的流程中读取、设定并维护关键参数。', 'screen.scenes.title': '场景编排', 'screen.scenes.sub': '可复用的空间逻辑', 'screen.scenes.body': '针对空间中的不同时刻保存、调用并复用场景。',
    'hardware.eyebrow': 'THE CONTROLLER LAYER', 'hardware.title': '稳住现场连接，<br /><em>再把能力交给软件。</em>', 'hardware.body': 'DALI 电源控制器 / 网关是项目的可靠入口：向上连接工程工作台，向下管理 DALI Line。通过 Type-C 或 LAN 接入，保持部署灵活，也为后续产品形态留出空间。', 'hardware.point1': 'Type-C 直连', 'hardware.point2': 'LAN 局域网', 'hardware.point3': '可选外部总线电源', 'hardware.note': 'Controller / Gateway / DALI Line',
    'placeholder.hardwareKicker': 'PRODUCT IMAGE SLOT', 'placeholder.hardwareTitle': 'Add controller render', 'placeholder.hardwareBody': '预留产品实拍 / 3D 渲染图位置',
    'markets.eyebrow': 'BUILT FOR THE SPACES THAT MATTER', 'markets.title': '从一间展厅，<br /><em>到一套可复制的系统。</em>', 'markets.intro': '同一套基础能力，适配不同空间对氛围、效率、可维护性和未来扩展的要求。', 'market.museum.title': '博物馆 / 展陈', 'market.museum.body': '精细亮度与色温控制，为展品和动线保留层次。', 'market.museum.tag': 'Curated light', 'market.retail.title': '商场 / 零售', 'market.retail.body': '快速复制区域策略，降低多店部署和调试成本。', 'market.retail.tag': 'Repeatable rollout', 'market.office.title': '办公 / 园区', 'market.office.body': '让分组、场景和时序跟随空间使用变化。', 'market.office.tag': 'Adaptive workspace', 'market.home.title': '家居 / 体验空间', 'market.home.body': '把专业调光能力转化为直观、易用的日常体验。', 'market.home.tag': 'Human scale',
    'future.eyebrow': 'THE NEXT LAYER', 'future.title': '今天把基础做好，<br /><em>明天让系统更懂现场。</em>', 'future.body': '面向未来的 AI 能力将建立在稳定的对象模型、工程快照和可追溯状态之上：从自然语言意图到场景建议，从异常信号到维护提示，逐步把经验变成可复用的系统能力。', 'future.tag1': 'Intent to scene', 'future.tag2': 'Anomaly signals', 'future.tag3': 'Guided commissioning', 'future.roadmap': 'ROADMAP / RESERVED',
    'platform.eyebrow': 'READY FOR YOUR ECOSYSTEM', 'platform.title': '跨平台，<br /><em>为每一种交付方式留出位置。</em>', 'platform.intro': '从工程师桌面到现场移动设备，保持同一套产品语言。品牌 Logo、平台截图和下载入口可按发布阶段逐步补齐。', 'platform.desktop': '桌面工程工作台', 'platform.mobile': '移动现场工具', 'placeholder.logoKicker': 'BRAND ASSET SLOT', 'placeholder.logoTitle': 'Add software logo', 'placeholder.logoBody': '预留软件 Logo / 品牌识别', 'platform.brand': 'Your brand layer', 'platform.brandSub': '可替换的品牌资产',
    'contact.eyebrow': 'START A CONVERSATION', 'contact.title': '让下一条 DALI Line，<br /><em>从更好的工程体验开始。</em>', 'contact.body': '面向系统集成商、照明 OEM、工程交付与渠道伙伴，获取产品资料、能力矩阵和合作讨论入口。', 'contact.primary': '联系产品团队 ↗', 'contact.secondary': '返回顶部 ↑', 'contact.note': '静态展示页 · 邮箱与下载链接可在发布前替换', 'footer.sub': 'Engineering clarity for every line.', 'footer.standard': 'IEC 62386 aligned · Product capability overview'
  },
  en: {
    'brand.sub': 'CONTROL PLATFORM', 'nav.capabilities': 'Capabilities', 'nav.workflow': 'Workflow', 'nav.software': 'Software', 'nav.markets': 'Markets', 'nav.contact': 'Talk to us ↗', 'control.languageLabel': 'Language',
    'hero.eyebrow': 'DALI CONTROL PLATFORM / V1.0', 'hero.title': 'Make every line <em>ready for the next scene.</em>', 'hero.description': 'A controller and engineering workspace for professional lighting projects. Built around international standards, it brings discovery, addressing, grouping, scenes, parameters and control into one deliverable path.', 'hero.primary': 'Explore capabilities ↓', 'hero.secondary': 'Get the partner brief ↗', 'hero.footnote': 'Built for commissioning teams, system integrators and lighting OEMs.', 'hero.visualLabel': 'LIVE WORKSPACE PREVIEW', 'hero.visualCaption': 'Engineering home · status overview', 'common.online': 'Online',
    'metric.lineLabel': 'DALI LINE', 'metric.lineSub': 'Ready to commission', 'metric.signalLabel': 'BUS SIGNAL', 'metric.signalSub': 'Stable link', 'standards.lead': 'Designed around the standards your projects already trust.', 'proof.platforms': 'supported platforms', 'proof.platformsSub': 'Windows · macOS · iOS · Android', 'proof.workflow': 'end-to-end workflow', 'proof.workflowSub': 'Less tool switching from scan to delivery', 'proof.scenes': 'scene slots', 'proof.scenesSub': 'Reusable spatial logic', 'proof.addresses': 'short-address view', 'proof.addressesSub': 'Organized around bus objects',
    'capabilities.eyebrow': 'ONE SYSTEM / MANY MOMENTS', 'capabilities.title': 'Give complexity <em>a clear place to work.</em>', 'capabilities.intro': 'From first device discovery to post-delivery maintenance, capabilities follow the real sequence of an engineering team. Every step has a clear object, state and outcome.', 'capability.discovery.title': 'Discovery & identity', 'capability.discovery.body': 'Build a controller and DALI Line view quickly, with fresh and extended scans plus connection state confirmation.', 'capability.discovery.tag': 'Commissioning start', 'capability.address.title': 'Addressing & topology', 'capability.address.body': 'Read, set and reassign short addresses while organizing work by address, group and bus object.', 'capability.address.tag': 'Addressing', 'capability.scene.title': 'Groups & scenes', 'capability.scene.body': 'Turn spatial intent into group and scene logic that can be read, reused and maintained.', 'capability.scene.tag': 'Space logic', 'capability.parameters.title': 'Parameters & batch setup', 'capability.parameters.body': 'Keep brightness, fade, range and device parameters in a clear read, set and batch-maintenance flow.', 'capability.parameters.tag': 'Fleet ready', 'capability.control.title': 'Live dimming & colour', 'capability.control.body': 'Control broadcast, groups or single addresses with switching, level, colour temperature and RGBWAF workflows.', 'capability.control.tag': 'DT8 control', 'capability.lifecycle.title': 'Connect, upgrade & deliver', 'capability.lifecycle.body': 'Type-C and LAN access, firmware upgrades and project snapshots carry the work from site commissioning into operations.', 'capability.lifecycle.tag': 'Lifecycle',
    'workflow.eyebrow': 'FROM FIRST SCAN TO LASTING VALUE', 'workflow.title': 'A deliverable <em>engineering rhythm.</em>', 'workflow.intro': 'Move from “it controls” to “it can be repeated, delivered and maintained”. Every stage keeps the next field action visible.', 'workflow.discover.title': 'Discover', 'workflow.discover.body': 'Find controllers and bus devices', 'workflow.address.title': 'Address', 'workflow.address.body': 'Build a clear address topology', 'workflow.compose.title': 'Compose', 'workflow.compose.body': 'Configure groups and scenes', 'workflow.tune.title': 'Tune', 'workflow.tune.body': 'Set key parameters in batches', 'workflow.operate.title': 'Operate', 'workflow.operate.body': 'Control and confirm on site', 'workflow.maintain.title': 'Maintain', 'workflow.maintain.body': 'Upgrade, diagnose and deliver',
    'software.eyebrow': 'SOFTWARE EXPERIENCE', 'software.title': 'Designed for field teams to <em>understand at a glance.</em>', 'software.intro': 'Professional capability should not disappear behind a complicated interface. The workspace organizes information around lines, objects, states and the next action.', 'screen.dashboard.title': 'Project overview', 'screen.dashboard.sub': 'Read project status fast', 'screen.dashboard.body': 'Devices, online state, faults and common zones come together in one view.', 'screen.control.title': 'Live control', 'screen.control.sub': 'Switch, level and colour temperature', 'screen.control.body': 'From broadcast to single address, every field action stays visible.', 'screen.parameters.title': 'Parameter setup', 'screen.parameters.sub': 'Batch maintenance and depth', 'screen.parameters.body': 'Read, set and maintain key parameters in one focused workflow.', 'screen.scenes.title': 'Scene composition', 'screen.scenes.sub': 'Reusable spatial logic', 'screen.scenes.body': 'Save, recall and reuse scenes for different spatial moments.',
    'hardware.eyebrow': 'THE CONTROLLER LAYER', 'hardware.title': 'Hold the field connection, <em>then let software scale the capability.</em>', 'hardware.body': 'The DALI power controller / gateway is the reliable project entry point: the engineering workspace above, the DALI Line below. Type-C and LAN keep deployment flexible while leaving room for future product forms.', 'hardware.point1': 'Direct Type-C', 'hardware.point2': 'LAN access', 'hardware.point3': 'Optional bus power', 'hardware.note': 'Controller / Gateway / DALI Line', 'placeholder.hardwareKicker': 'PRODUCT IMAGE SLOT', 'placeholder.hardwareTitle': 'Add controller render', 'placeholder.hardwareBody': 'Reserved for product photography / 3D render',
    'markets.eyebrow': 'BUILT FOR THE SPACES THAT MATTER', 'markets.title': 'From one gallery <em>to a repeatable system.</em>', 'markets.intro': 'One capability foundation, tuned for the atmosphere, efficiency, maintainability and future growth each space demands.', 'market.museum.title': 'Museums / exhibits', 'market.museum.body': 'Fine level and colour temperature control keeps depth around the collection and route.', 'market.museum.tag': 'Curated light', 'market.retail.title': 'Retail / mixed-use', 'market.retail.body': 'Replicate zone strategies quickly and lower multi-site commissioning cost.', 'market.retail.tag': 'Repeatable rollout', 'market.office.title': 'Workplace / campus', 'market.office.body': 'Let groups, scenes and schedules follow how the space is used.', 'market.office.tag': 'Adaptive workspace', 'market.home.title': 'Residential / experience', 'market.home.body': 'Translate professional dimming into intuitive, human-scale everyday moments.', 'market.home.tag': 'Human scale',
    'future.eyebrow': 'THE NEXT LAYER', 'future.title': 'Build the foundation today, <em>make the system more aware tomorrow.</em>', 'future.body': 'Future AI capabilities can build on stable object models, project snapshots and traceable state: from natural-language intent to scene suggestions, from anomaly signals to maintenance prompts, turning experience into reusable system capability.', 'future.tag1': 'Intent to scene', 'future.tag2': 'Anomaly signals', 'future.tag3': 'Guided commissioning', 'future.roadmap': 'ROADMAP / RESERVED', 'platform.eyebrow': 'READY FOR YOUR ECOSYSTEM', 'platform.title': 'Cross-platform, <em>ready for every delivery motion.</em>', 'platform.intro': 'Keep one product language from the engineer desktop to the field device. Add your brand mark, platform screenshots and download paths as the release matures.', 'platform.desktop': 'Desktop engineering workspace', 'platform.mobile': 'Mobile field tool', 'placeholder.logoKicker': 'BRAND ASSET SLOT', 'placeholder.logoTitle': 'Add software logo', 'placeholder.logoBody': 'Reserved for software logo / identity', 'platform.brand': 'Your brand layer', 'platform.brandSub': 'Replaceable brand asset',
    'contact.eyebrow': 'START A CONVERSATION', 'contact.title': 'Let the next DALI Line <em>start with a better engineering experience.</em>', 'contact.body': 'For system integrators, lighting OEMs, project delivery teams and channel partners: product material, capability matrix and partnership entry points.', 'contact.primary': 'Talk to the product team ↗', 'contact.secondary': 'Back to top ↑', 'contact.note': 'Static showcase · Replace email and download links before release', 'footer.sub': 'Engineering clarity for every line.', 'footer.standard': 'IEC 62386 aligned · Product capability overview'
  },
  ja: {
    'brand.sub': 'CONTROL PLATFORM', 'nav.capabilities': '機能', 'nav.workflow': '工程', 'nav.software': 'ソフトウェア', 'nav.markets': '用途', 'nav.contact': 'お問い合わせ ↗', 'control.languageLabel': '言語',
    'hero.eyebrow': 'DALI CONTROL PLATFORM / V1.0', 'hero.title': 'すべてのラインを、<em>次のシーンへ。</em>', 'hero.description': 'プロフェッショナル照明向けのコントローラーとエンジニアリングワークスペース。国際標準を軸に、検出、アドレス、グループ、シーン、パラメータ、制御を一つの運用フローへまとめます。', 'hero.primary': '機能を見る ↓', 'hero.secondary': '資料を入手 ↗', 'hero.footnote': 'コミッショニングチーム、システムインテグレーター、照明 OEM のために設計。', 'hero.visualLabel': 'LIVE WORKSPACE PREVIEW', 'hero.visualCaption': 'エンジニアリングホーム · 状態一覧', 'common.online': 'オンライン',
    'metric.lineLabel': 'DALI LINE', 'metric.lineSub': 'Ready to commission', 'metric.signalLabel': 'BUS SIGNAL', 'metric.signalSub': 'Stable link', 'standards.lead': '信頼される標準を中心に設計。', 'proof.platforms': '対応プラットフォーム', 'proof.platformsSub': 'Windows · macOS · iOS · Android', 'proof.workflow': '一つの工程フロー', 'proof.workflowSub': '検出から納品まで操作を集約', 'proof.scenes': 'シーンスロット', 'proof.scenesSub': '再利用できる空間ロジック', 'proof.addresses': 'ショートアドレス', 'proof.addressesSub': 'バスオブジェクトを中心に管理',
    'capabilities.eyebrow': 'ONE SYSTEM / MANY MOMENTS', 'capabilities.title': '複雑な工程を、<em>明快なワークスペースへ。</em>', 'capabilities.intro': '初回のデバイス検出から納品後の保守まで、現場チームの実際の順序に沿って機能を配置。各ステップに対象、状態、結果があります。', 'capability.discovery.title': '検出と識別', 'capability.discovery.body': 'コントローラーと DALI Line をすばやく可視化。新規検索、拡張検索、接続状態の確認に対応。', 'capability.discovery.tag': 'Commissioning start', 'capability.address.title': 'アドレスとトポロジー', 'capability.address.body': 'ショートアドレスの読み取り、設定、再割り当てを行い、アドレス、グループ、バスオブジェクトで整理。', 'capability.address.tag': 'Addressing', 'capability.scene.title': 'グループとシーン', 'capability.scene.body': '空間の意図を読み取り、再利用、保守できるグループとシーンへ。', 'capability.scene.tag': 'Space logic', 'capability.parameters.title': 'パラメータと一括設定', 'capability.parameters.body': '明るさ、フェード、範囲、デバイスパラメータを読み取り、設定、一括保守。', 'capability.parameters.tag': 'Fleet ready', 'capability.control.title': 'リアルタイム調光とカラー', 'capability.control.body': 'ブロードキャスト、グループ、単一アドレスで、オンオフ、レベル、色温度、RGBWAF を制御。', 'capability.control.tag': 'DT8 control', 'capability.lifecycle.title': '接続、更新、納品', 'capability.lifecycle.body': 'Type-C と LAN、ファームウェア更新、プロジェクトスナップショットで現場から運用へ。', 'capability.lifecycle.tag': 'Lifecycle',
    'workflow.eyebrow': 'FROM FIRST SCAN TO LASTING VALUE', 'workflow.title': '納品できる<em>エンジニアリングリズム。</em>', 'workflow.intro': '「制御できる」から「再現できる、納品できる、保守できる」へ。各段階で次の現場アクションを明確にします。', 'workflow.discover.title': 'Discover', 'workflow.discover.body': 'コントローラーとデバイスを検出', 'workflow.address.title': 'Address', 'workflow.address.body': 'アドレスとトポロジーを構築', 'workflow.compose.title': 'Compose', 'workflow.compose.body': 'グループとシーンを設定', 'workflow.tune.title': 'Tune', 'workflow.tune.body': '主要パラメータを一括設定', 'workflow.operate.title': 'Operate', 'workflow.operate.body': '現場で制御と確認', 'workflow.maintain.title': 'Maintain', 'workflow.maintain.body': '更新、診断、納品',
    'software.eyebrow': 'SOFTWARE EXPERIENCE', 'software.title': '現場チームが、<em>ひと目で理解できる設計。</em>', 'software.intro': '専門的な機能を複雑な画面の奥に隠しません。ライン、オブジェクト、状態、次の操作を軸に情報を整理し、現場の判断を支えます。', 'screen.dashboard.title': 'プロジェクト概要', 'screen.dashboard.sub': '状態をすばやく把握', 'screen.dashboard.body': 'デバイス、オンライン状態、障害、主要エリアを一つの画面に集約します。', 'screen.control.title': 'リアルタイム制御', 'screen.control.sub': 'オンオフ、レベル、色温度', 'screen.control.body': 'ブロードキャストから単一アドレスまで、現場操作を明確に表示します。', 'screen.parameters.title': 'パラメータ設定', 'screen.parameters.sub': '一括保守と詳細設定', 'screen.parameters.body': '主要パラメータを一つの流れで読み取り、設定、保守できます。', 'screen.scenes.title': 'シーン構成', 'screen.scenes.sub': '再利用できる空間ロジック', 'screen.scenes.body': '空間のさまざまな場面に合わせて、シーンを保存、呼び出し、再利用できます。',
    'hardware.eyebrow': 'THE CONTROLLER LAYER', 'hardware.title': '現場の接続を支え、<em>ソフトウェアへ能力を渡す。</em>', 'hardware.body': 'DALI 電源コントローラー / ゲートウェイは信頼できる入口。上位のワークスペースと下位の DALI Line をつなぎ、Type-C と LAN で柔軟な導入を支えます。', 'hardware.point1': 'Type-C 直結', 'hardware.point2': 'LAN 接続', 'hardware.point3': '外部バス電源（選択）', 'hardware.note': 'Controller / Gateway / DALI Line', 'placeholder.hardwareKicker': 'PRODUCT IMAGE SLOT', 'placeholder.hardwareTitle': 'Add controller render', 'placeholder.hardwareBody': '製品写真 / 3D レンダリング用の予約枠',
    'markets.eyebrow': 'BUILT FOR THE SPACES THAT MATTER', 'markets.title': '一つの展示室から、<em>再現できるシステムへ。</em>', 'markets.intro': '一つの基盤で、空間ごとの雰囲気、効率、保守性、将来拡張に対応。', 'market.museum.title': '美術館 / 展示', 'market.museum.body': '細かな明るさと色温度で、展示と動線に奥行きを。', 'market.museum.tag': 'Curated light', 'market.retail.title': '商業施設 / 小売', 'market.retail.body': 'ゾーン戦略をすばやく複製し、多拠点の調整コストを軽減。', 'market.retail.tag': 'Repeatable rollout', 'market.office.title': 'オフィス / キャンパス', 'market.office.body': 'グループ、シーン、スケジュールを空間の使い方に合わせる。', 'market.office.tag': 'Adaptive workspace', 'market.home.title': '住宅 / 体験空間', 'market.home.body': '専門的な調光を、直感的で人に寄り添う体験へ。', 'market.home.tag': 'Human scale',
    'future.eyebrow': 'THE NEXT LAYER', 'future.title': '今日、基盤を整え、<em>明日、現場を理解するシステムへ。</em>', 'future.body': '将来の AI 機能は、安定したオブジェクトモデル、工程スナップショット、追跡可能な状態を基盤にします。自然言語からのシーン提案、異常シグナル、保守提示へ、経験を再利用できる能力に変えていきます。', 'future.tag1': 'Intent to scene', 'future.tag2': 'Anomaly signals', 'future.tag3': 'Guided commissioning', 'future.roadmap': 'ROADMAP / RESERVED', 'platform.eyebrow': 'READY FOR YOUR ECOSYSTEM', 'platform.title': 'クロスプラットフォーム、<em>あらゆる納品形態に。</em>', 'platform.intro': 'エンジニアのデスクトップから現場のモバイルまで、同じプロダクト言語を維持。ブランド、スクリーンショット、ダウンロード導線を段階的に追加できます。', 'platform.desktop': 'デスクトップワークスペース', 'platform.mobile': 'モバイル現場ツール', 'placeholder.logoKicker': 'BRAND ASSET SLOT', 'placeholder.logoTitle': 'Add software logo', 'placeholder.logoBody': 'ソフトウェアロゴ / ブランド用の予約枠', 'platform.brand': 'Your brand layer', 'platform.brandSub': '差し替え可能なブランド素材',
    'contact.eyebrow': 'START A CONVERSATION', 'contact.title': '次の DALI Line を、<em>より良い工程体験から。</em>', 'contact.body': 'システムインテグレーター、照明 OEM、施工チーム、チャネルパートナー向けに、製品資料、機能マトリクス、協業窓口を用意しています。', 'contact.primary': 'プロダクトチームへ ↗', 'contact.secondary': 'トップへ ↑', 'contact.note': '静的展示ページ · 公開前にメールとダウンロードリンクを差し替え', 'footer.sub': 'Engineering clarity for every line.', 'footer.standard': 'IEC 62386 aligned · Product capability overview'
  }
};

for (const [locale, additions] of Object.entries(globalThis.daliAdditionalMessages || {})) {
  messages[locale] = { ...messages.en, ...(messages[locale] || {}), ...additions };
}

const screens = {
  dashboard: { image: 'assets/screenshots/dashboard.png', kicker: 'DALI WORKSPACE / DASHBOARD', key: 'screen.dashboard' },
  control: { image: 'assets/screenshots/live-control.png', kicker: 'DALI WORKSPACE / LIVE CONTROL', key: 'screen.control' },
  parameters: { image: 'assets/screenshots/parameters.png', kicker: 'DALI WORKSPACE / PARAMETERS', key: 'screen.parameters' },
  scenes: { image: 'assets/screenshots/scenes.png', kicker: 'DALI WORKSPACE / SCENES', key: 'screen.scenes' }
};

const themeOrder = ['dark', 'light', 'sky'];
const themeIcons = { dark: '◐', light: '☼', sky: '◉' };
const themeColors = { dark: '#09131f', light: '#f3f7f4', sky: '#f2f9fd' };
const state = { locale: localStorage.getItem('dali-locale') || 'zh-Hans', theme: localStorage.getItem('dali-theme') || 'dark' };

function applyLocale(locale) {
  state.locale = messages[locale] ? locale : 'zh-Hans';
  const documentLanguages = { 'zh-Hans': 'zh-CN', en: 'en', ja: 'ja-JP', fr: 'fr-FR', de: 'de-DE' };
  document.documentElement.lang = documentLanguages[state.locale];
  document.querySelectorAll('[data-i18n]').forEach((node) => {
    const value = messages[state.locale][node.dataset.i18n];
    if (value) node.innerHTML = value;
  });
  document.querySelector('#language-select').value = state.locale;
  document.querySelectorAll('[data-i18n-aria]').forEach((node) => {
    const value = messages[state.locale][node.dataset.i18nAria];
    if (value) {
      node.setAttribute('aria-label', value);
      node.setAttribute('title', value);
    }
  });
  localStorage.setItem('dali-locale', state.locale);
  updateThemeControl();
  updateScreen(document.querySelector('.software-tab.is-selected')?.dataset.screen || 'dashboard');
}

function applyTheme(theme) {
  state.theme = themeOrder.includes(theme) ? theme : 'dark';
  document.body.dataset.theme = state.theme;
  document.querySelector('meta[name="theme-color"]').content = themeColors[state.theme];
  updateThemeControl();
  localStorage.setItem('dali-theme', state.theme);
}

function updateThemeControl() {
  const button = document.querySelector('#theme-toggle');
  const currentIndex = themeOrder.indexOf(state.theme);
  const nextTheme = themeOrder[(currentIndex + 1) % themeOrder.length];
  const locale = messages[state.locale] || messages['zh-Hans'];
  const label = `${locale['control.themeLabel']}: ${locale[`theme.${state.theme}`]}. ${locale['control.themeNext']}: ${locale[`theme.${nextTheme}`]}`;
  button.textContent = themeIcons[state.theme];
  button.setAttribute('aria-label', label);
  button.setAttribute('title', label);
}

function updateScreen(name) {
  const screen = screens[name] || screens.dashboard;
  const locale = messages[state.locale];
  const tab = document.querySelector(`[data-screen="${name}"]`);
  document.querySelectorAll('.software-tab').forEach((item) => { const selected = item === tab; item.classList.toggle('is-selected', selected); item.setAttribute('aria-selected', String(selected)); });
  document.querySelector('#screen-image').src = screen.image;
  document.querySelector('#screen-image').alt = `${locale[`${screen.key}.title`]} screenshot`;
  document.querySelector('#screen-kicker').textContent = screen.kicker;
  document.querySelector('#screen-title').innerHTML = locale[`${screen.key}.title`];
  document.querySelector('#screen-description').innerHTML = locale[`${screen.key}.body`];
  document.querySelector('#screen-counter').textContent = `${String(Object.keys(screens).indexOf(name) + 1).padStart(2, '0')} / 04`;
}

document.querySelector('#language-select').addEventListener('change', (event) => applyLocale(event.target.value));
document.querySelector('#theme-toggle').addEventListener('click', () => {
  const nextIndex = (themeOrder.indexOf(state.theme) + 1) % themeOrder.length;
  applyTheme(themeOrder[nextIndex]);
});
document.querySelectorAll('.software-tab').forEach((tab) => tab.addEventListener('click', () => updateScreen(tab.dataset.screen)));
document.querySelectorAll('a[href^="#"]').forEach((link) => link.addEventListener('click', () => { document.body.classList.add('has-navigated'); }));
const backToTop = document.querySelector('#back-to-top');
function updateBackToTop() { backToTop.classList.toggle('is-visible', window.scrollY > 560); }
window.addEventListener('scroll', updateBackToTop, { passive: true });
backToTop.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));
applyTheme(state.theme);
applyLocale(state.locale);
updateBackToTop();
