globalThis.daliAdditionalMessages = {
  'zh-Hans': {
    'control.themeLabel': '色调主题', 'control.themeNext': '下一主题', 'control.backToTop': '返回页面顶部', 'theme.dark': '深色', 'theme.light': '清透亮色', 'theme.sky': '天蓝亮色',
    'platform.screenshotSlot': '截图占位', 'platform.windowsSub': '桌面工程工作台截图', 'platform.macSub': 'macOS 工程工作台截图', 'platform.iphoneSub': 'iOS 手机现场截图', 'platform.ipadSub': 'iPad 现场工作台截图', 'platform.androidPhoneSub': 'Android 手机现场截图', 'platform.androidPadSub': 'Android 平板工作台截图'
  },
  en: {
    'control.themeLabel': 'Colour theme', 'control.themeNext': 'Next theme', 'control.backToTop': 'Back to top', 'theme.dark': 'Dark', 'theme.light': 'Clear light', 'theme.sky': 'Sky blue light',
    'platform.screenshotSlot': 'SCREENSHOT SLOT', 'platform.windowsSub': 'Desktop engineering screenshot', 'platform.macSub': 'macOS engineering screenshot', 'platform.iphoneSub': 'iOS phone field screenshot', 'platform.ipadSub': 'iPad workspace screenshot', 'platform.androidPhoneSub': 'Android phone field screenshot', 'platform.androidPadSub': 'Android tablet workspace screenshot'
  },
  ja: {
    'control.themeLabel': 'カラーテーマ', 'control.themeNext': '次のテーマ', 'control.backToTop': 'ページ上部へ戻る', 'theme.dark': 'ダーク', 'theme.light': 'クリアライト', 'theme.sky': 'スカイブルーライト',
    'platform.screenshotSlot': 'スクリーンショット枠', 'platform.windowsSub': 'デスクトップ画面', 'platform.macSub': 'macOS ワークスペース画面', 'platform.iphoneSub': 'iOS 現場画面', 'platform.ipadSub': 'iPad ワークスペース画面', 'platform.androidPhoneSub': 'Android スマートフォン画面', 'platform.androidPadSub': 'Android タブレット画面'
  },
  fr: {
    'brand.sub': 'PLATEFORME DE CONTRÔLE', 'nav.capabilities': 'Capacités', 'nav.workflow': 'Parcours', 'nav.software': 'Logiciel', 'nav.markets': 'Secteurs', 'nav.contact': 'Nous contacter ↗', 'control.languageLabel': 'Langue',
    'hero.eyebrow': 'DALI CONTROL PLATFORM / V1.0', 'hero.title': 'Chaque ligne est prête <em>pour la prochaine scène.</em>', 'hero.description': 'Un contrôleur et un espace d’ingénierie pour les projets d’éclairage professionnels. Fondé sur les normes internationales, l’ensemble réunit détection, adressage, groupes, scènes, paramètres et commande dans un parcours prêt à livrer.', 'hero.primary': 'Explorer les capacités ↓', 'hero.secondary': 'Recevoir le dossier partenaire ↗', 'hero.footnote': 'Conçu pour les équipes de mise en service, les intégrateurs et les fabricants d’éclairage.', 'hero.visualLabel': 'APERÇU DE L’ESPACE DE TRAVAIL', 'hero.visualCaption': 'Accueil projet · vue d’ensemble', 'common.online': 'En ligne',
    'metric.lineLabel': 'LIGNE DALI', 'metric.lineSub': 'Prête pour la mise en service', 'metric.signalLabel': 'SIGNAL DU BUS', 'metric.signalSub': 'Liaison stable', 'standards.lead': 'Conçu autour des normes auxquelles vos projets font déjà confiance.', 'proof.platforms': 'plateformes prises en charge', 'proof.platformsSub': 'Windows · macOS · iOS · Android', 'proof.workflow': 'parcours de bout en bout', 'proof.workflowSub': 'Moins d’outils entre détection et livraison', 'proof.scenes': 'emplacements de scène', 'proof.scenesSub': 'Une logique spatiale réutilisable', 'proof.addresses': 'adresses courtes', 'proof.addressesSub': 'Organisation centrée sur les objets du bus',
    'capabilities.eyebrow': 'UN SYSTÈME / PLUSIEURS MOMENTS', 'capabilities.title': 'Donnez à la complexité <em>un espace de travail clair.</em>', 'capabilities.intro': 'De la première détection à la maintenance après livraison, les capacités suivent l’ordre réel du travail d’ingénierie. Chaque étape présente un objet, un état et un résultat clairs.',
    'capability.discovery.title': 'Détection et identification', 'capability.discovery.body': 'Construisez rapidement une vue du contrôleur et de la ligne DALI, avec recherche initiale, recherche étendue et confirmation de l’état de connexion.', 'capability.discovery.tag': 'Début de mise en service',
    'capability.address.title': 'Adressage et topologie', 'capability.address.body': 'Lisez, définissez et réattribuez les adresses courtes, puis organisez le terrain par adresse, groupe et objet du bus.', 'capability.address.tag': 'Adressage',
    'capability.scene.title': 'Groupes et scènes', 'capability.scene.body': 'Transformez l’intention spatiale en groupes et scènes lisibles, réutilisables et maintenables.', 'capability.scene.tag': 'Logique spatiale',
    'capability.parameters.title': 'Paramètres et configuration par lot', 'capability.parameters.body': 'Regroupez luminosité, fondu, plages et paramètres des appareils dans un flux clair de lecture, d’écriture et de maintenance par lot.', 'capability.parameters.tag': 'Prêt pour le parc',
    'capability.control.title': 'Variation et couleur en direct', 'capability.control.body': 'Commandez la diffusion, les groupes ou une adresse unique : marche/arrêt, niveau, température de couleur et RGBWAF.', 'capability.control.tag': 'Commande DT8',
    'capability.lifecycle.title': 'Connecter, mettre à jour, livrer', 'capability.lifecycle.body': 'Les accès Type-C et LAN, les mises à jour du firmware et les instantanés projet prolongent la mise en service jusqu’à l’exploitation.', 'capability.lifecycle.tag': 'Cycle de vie',
    'workflow.eyebrow': 'DU PREMIER SCAN À UNE VALEUR DURABLE', 'workflow.title': 'Un rythme d’ingénierie <em>prêt à livrer.</em>', 'workflow.intro': 'Passez de « ça commande » à « c’est reproductible, livrable et maintenable ». Chaque phase rend visible l’action terrain suivante.', 'workflow.discover.title': 'Détecter', 'workflow.discover.body': 'Trouver les contrôleurs et appareils du bus', 'workflow.address.title': 'Adresser', 'workflow.address.body': 'Construire une topologie claire', 'workflow.compose.title': 'Composer', 'workflow.compose.body': 'Configurer groupes et scènes', 'workflow.tune.title': 'Régler', 'workflow.tune.body': 'Définir les paramètres par lot', 'workflow.operate.title': 'Exploiter', 'workflow.operate.body': 'Commander et confirmer sur site', 'workflow.maintain.title': 'Maintenir', 'workflow.maintain.body': 'Mettre à jour, diagnostiquer et livrer',
    'software.eyebrow': 'EXPÉRIENCE LOGICIELLE', 'software.title': 'Conçu pour être <em>compris d’un coup d’œil.</em>', 'software.intro': 'Les capacités professionnelles ne doivent pas disparaître derrière une interface complexe. L’espace organise les informations autour des lignes, objets, états et prochaines actions.', 'screen.dashboard.title': 'Vue d’ensemble du projet', 'screen.dashboard.sub': 'Évaluer rapidement l’état', 'screen.dashboard.body': 'Appareils, état en ligne, défauts et zones principales sont réunis dans une même vue.', 'screen.control.title': 'Commande en direct', 'screen.control.sub': 'Marche, niveau et température', 'screen.control.body': 'De la diffusion à l’adresse unique, chaque action terrain reste visible.', 'screen.parameters.title': 'Configuration des paramètres', 'screen.parameters.sub': 'Maintenance par lot et réglages', 'screen.parameters.body': 'Lisez, définissez et maintenez les paramètres essentiels dans un flux concentré.', 'screen.scenes.title': 'Composition des scènes', 'screen.scenes.sub': 'Logique spatiale réutilisable', 'screen.scenes.body': 'Enregistrez, rappelez et réutilisez les scènes selon les moments du lieu.',
    'hardware.eyebrow': 'LA COUCHE CONTRÔLEUR', 'hardware.title': 'Fiabilisez la connexion terrain, <em>puis laissez le logiciel déployer les capacités.</em>', 'hardware.body': 'Le contrôleur d’alimentation / la passerelle DALI constitue l’entrée fiable du projet : l’espace d’ingénierie au-dessus, la ligne DALI au-dessous. Type-C et LAN assurent un déploiement flexible et ouvrent la voie aux futures variantes produit.', 'hardware.point1': 'Type-C direct', 'hardware.point2': 'Accès LAN', 'hardware.point3': 'Alimentation bus en option', 'hardware.note': 'Contrôleur / Passerelle / Ligne DALI', 'placeholder.hardwareKicker': 'EMPLACEMENT IMAGE PRODUIT', 'placeholder.hardwareTitle': 'Ajouter le rendu du contrôleur', 'placeholder.hardwareBody': 'Réservé à une photo produit ou un rendu 3D',
    'markets.eyebrow': 'CONÇU POUR LES ESPACES QUI COMPTENT', 'markets.title': 'D’une galerie <em>à un système reproductible.</em>', 'markets.intro': 'Une même base de capacités, adaptée à l’ambiance, l’efficacité, la maintenabilité et l’évolution de chaque espace.', 'market.museum.title': 'Musées / expositions', 'market.museum.body': 'Un contrôle fin du niveau et de la température de couleur préserve la profondeur des œuvres et des parcours.', 'market.museum.tag': 'Lumière composée', 'market.retail.title': 'Commerce / espaces mixtes', 'market.retail.body': 'Répliquez rapidement les stratégies de zone et réduisez le coût des déploiements multisites.', 'market.retail.tag': 'Déploiement reproductible', 'market.office.title': 'Bureaux / campus', 'market.office.body': 'Faites évoluer groupes, scènes et horaires avec les usages du lieu.', 'market.office.tag': 'Espace adaptatif', 'market.home.title': 'Résidentiel / expérience', 'market.home.body': 'Transformez la variation professionnelle en moments quotidiens intuitifs.', 'market.home.tag': 'À l’échelle humaine',
    'future.eyebrow': 'LA PROCHAINE COUCHE', 'future.title': 'Construisez les fondations aujourd’hui, <em>rendez le système plus conscient demain.</em>', 'future.body': 'Les futures capacités d’IA pourront s’appuyer sur des modèles d’objets stables, des instantanés projet et des états traçables : de l’intention en langage naturel aux suggestions de scène, des signaux anormaux aux conseils de maintenance.', 'future.tag1': 'Intention vers scène', 'future.tag2': 'Signaux d’anomalie', 'future.tag3': 'Mise en service guidée', 'future.roadmap': 'FEUILLE DE ROUTE / RÉSERVÉ',
    'platform.eyebrow': 'PRÊT POUR VOTRE ÉCOSYSTÈME', 'platform.title': 'Multiplateforme, <em>prêt pour chaque mode de livraison.</em>', 'platform.intro': 'Conservez un même langage produit, du poste d’ingénierie aux appareils de terrain. Ajoutez les captures de chaque plateforme et les accès de téléchargement au rythme de la publication.', 'platform.desktop': 'Espace d’ingénierie de bureau', 'platform.mobile': 'Outil mobile de terrain', 'platform.screenshotSlot': 'CAPTURE À AJOUTER', 'platform.windowsSub': 'Capture du poste d’ingénierie', 'platform.macSub': 'Capture de l’espace macOS', 'platform.iphoneSub': 'Capture terrain sur iPhone', 'platform.ipadSub': 'Capture de l’espace iPad', 'platform.androidPhoneSub': 'Capture terrain sur téléphone Android', 'platform.androidPadSub': 'Capture de l’espace tablette Android', 'placeholder.logoKicker': 'EMPLACEMENT DE MARQUE', 'placeholder.logoTitle': 'Ajouter le logo du logiciel', 'placeholder.logoBody': 'Réservé au logo et à l’identité du logiciel', 'platform.brand': 'Votre couche de marque', 'platform.brandSub': 'Ressource de marque remplaçable',
    'control.themeLabel': 'Thème de couleur', 'control.themeNext': 'Thème suivant', 'control.backToTop': 'Retour en haut de la page', 'theme.dark': 'Sombre', 'theme.light': 'Clair', 'theme.sky': 'Clair bleu ciel',
    'contact.eyebrow': 'COMMENÇONS LA CONVERSATION', 'contact.title': 'Faites commencer la prochaine ligne DALI <em>par une meilleure expérience d’ingénierie.</em>', 'contact.body': 'Pour les intégrateurs, fabricants d’éclairage, équipes projet et partenaires de distribution : documentation produit, matrice de capacités et échanges de partenariat.', 'contact.primary': 'Parler à l’équipe produit ↗', 'contact.secondary': 'Retour en haut ↑', 'contact.note': 'Page statique · Remplacer l’e-mail et les liens avant publication', 'footer.sub': 'Une ingénierie claire pour chaque ligne.', 'footer.standard': 'Aligné sur IEC 62386 · Vue d’ensemble des capacités produit'
  },
  de: {
    'brand.sub': 'STEUERUNGSPLATTFORM', 'nav.capabilities': 'Funktionen', 'nav.workflow': 'Ablauf', 'nav.software': 'Software', 'nav.markets': 'Branchen', 'nav.contact': 'Kontakt ↗', 'control.languageLabel': 'Sprache',
    'hero.eyebrow': 'DALI CONTROL PLATFORM / V1.0', 'hero.title': 'Jede Linie ist <em>bereit für die nächste Szene.</em>', 'hero.description': 'Controller und Engineering-Arbeitsplatz für professionelle Beleuchtungsprojekte. Auf Basis internationaler Standards werden Erkennung, Adressierung, Gruppen, Szenen, Parameter und Steuerung in einem lieferbaren Ablauf gebündelt.', 'hero.primary': 'Funktionen entdecken ↓', 'hero.secondary': 'Partnerunterlagen anfordern ↗', 'hero.footnote': 'Entwickelt für Inbetriebnahmeteams, Systemintegratoren und Leuchtenhersteller.', 'hero.visualLabel': 'LIVE-VORSCHAU DES ARBEITSBEREICHS', 'hero.visualCaption': 'Projektstart · Statusübersicht', 'common.online': 'Online',
    'metric.lineLabel': 'DALI-LINIE', 'metric.lineSub': 'Bereit zur Inbetriebnahme', 'metric.signalLabel': 'BUSSIGNAL', 'metric.signalSub': 'Stabile Verbindung', 'standards.lead': 'Entwickelt rund um die Standards, denen Ihre Projekte bereits vertrauen.', 'proof.platforms': 'unterstützte Plattformen', 'proof.platformsSub': 'Windows · macOS · iOS · Android', 'proof.workflow': 'durchgängiger Ablauf', 'proof.workflowSub': 'Weniger Werkzeugwechsel bis zur Übergabe', 'proof.scenes': 'Szenenspeicher', 'proof.scenesSub': 'Wiederverwendbare Raumlogik', 'proof.addresses': 'Kurzadressenansicht', 'proof.addressesSub': 'Nach Busobjekten organisiert',
    'capabilities.eyebrow': 'EIN SYSTEM / VIELE MOMENTE', 'capabilities.title': 'Komplexität bekommt <em>einen klaren Arbeitsplatz.</em>', 'capabilities.intro': 'Von der ersten Geräteerkennung bis zur Wartung nach der Übergabe folgen die Funktionen dem realen Ablauf des Engineering-Teams. Jeder Schritt hat Objekt, Status und Ergebnis.',
    'capability.discovery.title': 'Erkennung und Identität', 'capability.discovery.body': 'Controller und DALI-Linie schnell erfassen, mit neuer und erweiterter Suche sowie Bestätigung des Verbindungsstatus.', 'capability.discovery.tag': 'Start der Inbetriebnahme',
    'capability.address.title': 'Adressierung und Topologie', 'capability.address.body': 'Kurzadressen lesen, setzen und neu vergeben; Arbeiten nach Adresse, Gruppe und Busobjekt organisieren.', 'capability.address.tag': 'Adressierung',
    'capability.scene.title': 'Gruppen und Szenen', 'capability.scene.body': 'Räumliche Absichten in lesbare, wiederverwendbare und wartbare Gruppen- und Szenenlogik überführen.', 'capability.scene.tag': 'Raumlogik',
    'capability.parameters.title': 'Parameter und Stapelkonfiguration', 'capability.parameters.body': 'Helligkeit, Überblendung, Bereiche und Geräteparameter in einem klaren Lese-, Schreib- und Wartungsablauf zusammenfassen.', 'capability.parameters.tag': 'Flottenbereit',
    'capability.control.title': 'Live-Dimmung und Farbe', 'capability.control.body': 'Broadcast, Gruppen oder Einzeladressen mit Schalten, Niveau, Farbtemperatur und RGBWAF steuern.', 'capability.control.tag': 'DT8-Steuerung',
    'capability.lifecycle.title': 'Verbinden, aktualisieren, übergeben', 'capability.lifecycle.body': 'Type-C- und LAN-Zugang, Firmware-Updates und Projekt-Snapshots führen von der Inbetriebnahme in den Betrieb.', 'capability.lifecycle.tag': 'Lebenszyklus',
    'workflow.eyebrow': 'VOM ERSTEN SCAN ZU DAUERHAFTEM WERT', 'workflow.title': 'Ein lieferbarer <em>Engineering-Rhythmus.</em>', 'workflow.intro': 'Von „es steuert“ zu „es ist wiederholbar, lieferbar und wartbar“. Jede Phase zeigt die nächste Aktion vor Ort.', 'workflow.discover.title': 'Erkennen', 'workflow.discover.body': 'Controller und Busgeräte finden', 'workflow.address.title': 'Adressieren', 'workflow.address.body': 'Klare Adresstopologie aufbauen', 'workflow.compose.title': 'Komponieren', 'workflow.compose.body': 'Gruppen und Szenen konfigurieren', 'workflow.tune.title': 'Abstimmen', 'workflow.tune.body': 'Schlüsselparameter stapelweise setzen', 'workflow.operate.title': 'Betreiben', 'workflow.operate.body': 'Vor Ort steuern und bestätigen', 'workflow.maintain.title': 'Warten', 'workflow.maintain.body': 'Aktualisieren, diagnostizieren und übergeben',
    'software.eyebrow': 'SOFTWARE-ERLEBNIS', 'software.title': 'Für Teams vor Ort, <em>auf einen Blick verständlich.</em>', 'software.intro': 'Professionelle Funktionen dürfen nicht hinter einer komplizierten Oberfläche verschwinden. Der Arbeitsplatz ordnet Informationen nach Linien, Objekten, Zuständen und nächster Aktion.', 'screen.dashboard.title': 'Projektübersicht', 'screen.dashboard.sub': 'Projektstatus schnell erfassen', 'screen.dashboard.body': 'Geräte, Online-Status, Fehler und wichtige Bereiche werden in einer Ansicht zusammengefasst.', 'screen.control.title': 'Live-Steuerung', 'screen.control.sub': 'Schalten, Niveau und Farbtemperatur', 'screen.control.body': 'Von Broadcast bis Einzeladresse bleibt jede Aktion vor Ort sichtbar.', 'screen.parameters.title': 'Parameterkonfiguration', 'screen.parameters.sub': 'Stapelwartung und Detailtiefe', 'screen.parameters.body': 'Schlüsselparameter in einem fokussierten Ablauf lesen, setzen und warten.', 'screen.scenes.title': 'Szenenkomposition', 'screen.scenes.sub': 'Wiederverwendbare Raumlogik', 'screen.scenes.body': 'Szenen für verschiedene Raummomente speichern, aufrufen und wiederverwenden.',
    'hardware.eyebrow': 'DIE CONTROLLER-EBENE', 'hardware.title': 'Feldverbindung stabil halten, <em>dann die Funktionen per Software skalieren.</em>', 'hardware.body': 'Der DALI-Stromcontroller / das Gateway ist der verlässliche Projekteinstieg: oben der Engineering-Arbeitsplatz, unten die DALI-Linie. Type-C und LAN halten die Bereitstellung flexibel und schaffen Raum für weitere Produktformen.', 'hardware.point1': 'Direktes Type-C', 'hardware.point2': 'LAN-Zugang', 'hardware.point3': 'Optionale Busversorgung', 'hardware.note': 'Controller / Gateway / DALI-Linie', 'placeholder.hardwareKicker': 'PLATZ FÜR PRODUKTBILD', 'placeholder.hardwareTitle': 'Controller-Rendering einfügen', 'placeholder.hardwareBody': 'Reserviert für Produktfoto oder 3D-Rendering',
    'markets.eyebrow': 'FÜR RÄUME, DIE ZÄHLEN', 'markets.title': 'Von einer Galerie <em>zum wiederholbaren System.</em>', 'markets.intro': 'Eine gemeinsame Basis, abgestimmt auf Atmosphäre, Effizienz, Wartbarkeit und Wachstum jedes Raums.', 'market.museum.title': 'Museen / Ausstellungen', 'market.museum.body': 'Feine Niveau- und Farbtemperatursteuerung bewahrt Tiefe rund um Exponate und Wege.', 'market.museum.tag': 'Kuratierte Beleuchtung', 'market.retail.title': 'Einzelhandel / Mischnutzung', 'market.retail.body': 'Zonenstrategien schnell replizieren und Aufwand bei mehreren Standorten reduzieren.', 'market.retail.tag': 'Wiederholbare Einführung', 'market.office.title': 'Arbeitsplatz / Campus', 'market.office.body': 'Gruppen, Szenen und Zeitpläne folgen der tatsächlichen Raumnutzung.', 'market.office.tag': 'Adaptiver Arbeitsplatz', 'market.home.title': 'Wohnen / Erlebnisraum', 'market.home.body': 'Professionelle Dimmung wird zu intuitiven, menschlichen Alltagsmomenten.', 'market.home.tag': 'Menschlicher Maßstab',
    'future.eyebrow': 'DIE NÄCHSTE EBENE', 'future.title': 'Heute das Fundament bauen, <em>morgen das System aufmerksamer machen.</em>', 'future.body': 'Künftige KI-Funktionen können auf stabilen Objektmodellen, Projekt-Snapshots und nachvollziehbaren Zuständen aufbauen: von natürlicher Sprache zu Szenenvorschlägen, von Anomaliesignalen zu Wartungshinweisen.', 'future.tag1': 'Absicht zur Szene', 'future.tag2': 'Anomaliesignale', 'future.tag3': 'Geführte Inbetriebnahme', 'future.roadmap': 'ROADMAP / RESERVIERT',
    'platform.eyebrow': 'BEREIT FÜR IHR ÖKOSYSTEM', 'platform.title': 'Plattformübergreifend, <em>bereit für jede Übergabeform.</em>', 'platform.intro': 'Eine Produktsprache vom Engineering-Desktop bis zum mobilen Feldgerät. Plattform-Screenshots und Downloadwege können mit der Veröffentlichung ergänzt werden.', 'platform.desktop': 'Desktop-Engineering-Arbeitsplatz', 'platform.mobile': 'Mobiles Feldwerkzeug', 'platform.screenshotSlot': 'SCREENSHOT-PLATZ', 'platform.windowsSub': 'Screenshot des Desktop-Arbeitsplatzes', 'platform.macSub': 'Screenshot des macOS-Arbeitsplatzes', 'platform.iphoneSub': 'iPhone-Screenshot für den Feldeinsatz', 'platform.ipadSub': 'Screenshot des iPad-Arbeitsplatzes', 'platform.androidPhoneSub': 'Android-Smartphone im Feldeinsatz', 'platform.androidPadSub': 'Screenshot des Android-Tablet-Arbeitsplatzes', 'placeholder.logoKicker': 'PLATZ FÜR MARKENASSET', 'placeholder.logoTitle': 'Softwarelogo einfügen', 'placeholder.logoBody': 'Reserviert für Softwarelogo und Markenidentität', 'platform.brand': 'Ihre Markenebene', 'platform.brandSub': 'Austauschbares Markenasset',
    'control.themeLabel': 'Farbthema', 'control.themeNext': 'Nächstes Thema', 'control.backToTop': 'Zurück zum Seitenanfang', 'theme.dark': 'Dunkel', 'theme.light': 'Klar und hell', 'theme.sky': 'Helles Himmelblau',
    'contact.eyebrow': 'INS GESPRÄCH KOMMEN', 'contact.title': 'Die nächste DALI-Linie beginnt <em>mit einem besseren Engineering-Erlebnis.</em>', 'contact.body': 'Für Systemintegratoren, Leuchtenhersteller, Projektteams und Vertriebspartner: Produktunterlagen, Funktionsmatrix und Partnerschaftsgespräche.', 'contact.primary': 'Mit dem Produktteam sprechen ↗', 'contact.secondary': 'Nach oben ↑', 'contact.note': 'Statische Präsentation · E-Mail und Downloadlinks vor Veröffentlichung ersetzen', 'footer.sub': 'Engineering-Klarheit für jede Linie.', 'footer.standard': 'An IEC 62386 ausgerichtet · Produktfunktionsübersicht'
  }
};
